# Generated by Django 4.2.11 on 2025-09-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_icon', models.CharField(blank=True, max_length=50)),
                ('points_required', models.PositiveIntegerField()),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('points_per_minute', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km', max_digits=8, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('activity_date', models.DateField()),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date', '-date_logged'],
            },
        ),
    ]
